### Crear un paciente nuevo
POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "Sarah Connor",
  "dateOfBirth": "1979-05-12",
  "ssn": "120579-ABC",
  "gender": "female",
  "occupation": "Waitress"
}


